apiVersion: v1
kind: Service
metadata:
  name: oauth
  labels:
    app: oauth
spec:
  ports:
  - name: oauth
    port: 3000
    targetPort: 3000
    nodePort: 31300
  selector:
    app: oauth
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth
  namespace: default
  labels:
    app: oauth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oauth
  template:
    metadata:
      labels:
        app: oauth
    spec:
      containers:
      - name: oauth
        image: 171170093330.dkr.ecr.eu-central-1.amazonaws.com/oauth2-oidc-debugger:1.0
        imagePullPolicy: "IfNotPresent"
        ports:
        - name: http
          containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
